#!/bin/bash
set -ex

if [[ -z "$1" ]]; then
    echo "Usage: $0 <package-name>"
    exit 1
fi

if [[ -z "$VIRTUAL_ENV" ]]; then
    echo "No active virtualenv found"
    exit 1
fi

if [[  "`uname`" == "Darwin" ]]; then
    LIB_DIR='/usr/local/lib/python2.7/site-packages'
else
    LIB_DIR='/usr/lib/python2.7/dist-packages'
fi

if [[ ! -e "$LIB_DIR/$1" ]]; then
    echo "Package $1 seems not to be installed system-wide"
fi

echo "Implanting $1 package to virtualenv $VIRTUAL_ENV"
ln -fsv $LIB_DIR/$1 $VIRTUAL_ENV/lib/python2.7/site-packages/
